"""
One-time script: geocode all D1 venues and write/update venue_coordinates.py.

Usage:
    python dashboard/scripts/build_venue_coords.py

Requires: geopy  (pip install geopy)
This script is NOT run at dashboard startup — it's a build-time tool.
"""

from __future__ import annotations

import asyncio
import os
import sys
import time

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_SRC = os.path.join(_ROOT, "src")
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)
sys.path.insert(0, _ROOT)


async def collect_teams() -> list:
    """Fetch all D1 teams from the service layer."""
    from cbb_mcp.services import teams as teams_svc
    from cbb_mcp.services.resolver import resolve
    from cbb_mcp.sources.base import DataCapability

    print("Fetching team list from ESPN...")
    try:
        teams = await resolve(DataCapability.TEAM_SEARCH, "search_teams", query="")
        print(f"  Found {len(teams)} teams")
        return teams
    except Exception as e:
        print(f"  Error: {e}")
        return []


async def geocode_teams(teams: list) -> dict[str, tuple[float, float]]:
    """Geocode each team's venue city/state using Nominatim."""
    from geopy.geocoders import Nominatim
    from geopy.exc import GeocoderTimedOut, GeocoderUnavailable
    from cbb_mcp.services import teams as teams_svc

    geolocator = Nominatim(user_agent="cbb-dashboard-builder/1.0")
    coords: dict[str, tuple[float, float]] = {}

    # Load existing coords to avoid re-geocoding
    try:
        from dashboard.data.venue_coordinates import VENUE_COORDS
        coords.update(VENUE_COORDS)
        print(f"Loaded {len(coords)} existing coordinates")
    except ImportError:
        pass

    print(f"\nGeocoding {len(teams)} teams (skipping already-known)...")
    new_count = 0

    for i, team in enumerate(teams):
        name = team.name
        if name in coords:
            continue

        # Try to get full team info with venue
        try:
            full_team = await teams_svc.get_team(name)
            venue = getattr(full_team, "venue", None)
            if venue and venue.city and venue.state:
                query = f"{venue.city}, {venue.state}, USA"
                try:
                    location = geolocator.geocode(query, timeout=10)
                    if location:
                        coords[name] = (location.latitude, location.longitude)
                        print(f"  [{i+1}/{len(teams)}] {name}: ({location.latitude:.4f}, {location.longitude:.4f})")
                        new_count += 1
                        time.sleep(1.1)  # Nominatim rate limit: 1 req/sec
                        continue
                except (GeocoderTimedOut, GeocoderUnavailable) as e:
                    print(f"  [{i+1}/{len(teams)}] {name}: geocoder error ({e})")
                    time.sleep(2)
        except Exception as e:
            pass

        print(f"  [{i+1}/{len(teams)}] {name}: no coords found")

    print(f"\nAdded {new_count} new coordinates. Total: {len(coords)}")
    return coords


def write_coords_file(coords: dict[str, tuple[float, float]]) -> None:
    """Write the updated VENUE_COORDS dict to venue_coordinates.py."""
    _ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    out_path = os.path.join(_ROOT, "dashboard", "data", "venue_coordinates.py")

    # Import existing STATE_CENTROIDS to preserve them
    try:
        from dashboard.data.venue_coordinates import STATE_CENTROIDS
    except ImportError:
        STATE_CENTROIDS = {}

    lines = [
        '"""',
        "Static venue coordinates for D1 college basketball programs.",
        "Keys match team names as returned by ESPN API.",
        "Generated by scripts/build_venue_coords.py",
        '"""',
        "",
        "VENUE_COORDS: dict[str, tuple[float, float]] = {",
    ]

    for name, (lat, lon) in sorted(coords.items()):
        safe_name = name.replace('"', '\\"')
        lines.append(f'    "{safe_name}": ({lat:.4f}, {lon:.4f}),')

    lines.append("}")
    lines.append("")

    # Preserve STATE_CENTROIDS
    lines.append("STATE_CENTROIDS: dict[str, tuple[float, float]] = {")
    for abbr, (lat, lon) in sorted(STATE_CENTROIDS.items()):
        lines.append(f'    "{abbr}": ({lat:.4f}, {lon:.4f}),')
    lines.append("}")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nWritten to {out_path}")


async def main():
    teams = await collect_teams()
    if not teams:
        print("No teams found. Exiting.")
        return

    coords = await geocode_teams(teams)
    write_coords_file(coords)
    print("Done!")


if __name__ == "__main__":
    asyncio.run(main())
